version: '3.6'

services:
  web:
    build: .
    command: > 
            bash -c
            "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py init_services &&
             python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - celery
      - celery-beat
    env_file:
      - .env

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A payment_health worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A payment_health beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
